/**
 * Environment variable types for EdgeOne Edge Functions
 */

export interface Environment {
  // APNs Configuration
  APNS_TOPIC?: string;
  APNS_KEY_ID?: string;
  APNS_TEAM_ID?: string;
  APNS_PRIVATE_KEY?: string;
  APNS_USE_SANDBOX?: string;

  // Proxy Configuration
  ENABLE_APNS_PROXY?: string;
  APNS_PROXY_URL?: string;
  APNS_PROXY_SECRET?: string;

  // Authentication
  AUTH_CREDENTIALS?: string;

  // Limits
  MAX_BATCH_PUSH_COUNT?: string;

  // Feature Flags
  ENABLE_REGISTER?: string;
  ENABLE_DEVICE_COUNT?: string;

  // Logging
  LOG_LEVEL?: 'DEBUG' | 'INFO' | 'WARN' | 'ERROR';

  // Internal (auto-generated by handlers)
  REQUEST_URL?: string;
}
